spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tedu_store?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
  jackson:
    default-property-inclusion: non_null
  servlet:
    multipart:
      max-file-size: 102400000
      file-size-threshold: 1024

mybatis:
  mapper-locations: mapper/*.xml

